# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: postgres-single
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/order:/var/lib/postgresql/data
      - ./init/order/init.sql:/docker-entrypoint-initdb.d/init.sql:ro


  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    container_name: pdamin-single
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password

