version: '3.9'

services:
  order-service:
    image: order-service
    ports:
      - "8082:8082"
    build:
      context: ../../order-microservice
      dockerfile: ../order-microservice/Dockerfile
    container_name: order-microservice-manual
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    container_name: postgres-single
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/order:/var/lib/postgresql/data
      - ./init/order/init.sql:/docker-entrypoint-initdb.d/init.sql


  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    container_name: pdamin-single
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password

